"""add entitlements colum to subscriptions

Revision ID: 00505e194e67
Revises: ed2e8bc077cc
Create Date: 2026-03-20 18:15:21.105868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00505e194e67'
down_revision: Union[str, Sequence[str], None] = 'ed2e8bc077cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('entitlements', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'::text[]"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'entitlements')
    # ### end Alembic commands ###
