"""add subscriptions table and soft delete columns to profiles

Revision ID: 8ee05b912b69
Revises: 2da9b2bb12a4
Create Date: 2026-03-19 18:07:46.690882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee05b912b69'
down_revision: Union[str, Sequence[str], None] = '2da9b2bb12a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'premium', name='subscriptionplan'), server_default=sa.text("'free'::subscriptionplan"), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'trialing', name='subscriptionstatus'), server_default=sa.text("'active'::subscriptionstatus"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revenuecat_customer_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.Enum('stripe', 'apple', 'google_play', name='subscriptionprovider'), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.add_column('profiles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_profiles_deleted_at'), 'profiles', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_deleted_at'), table_name='profiles')
    op.drop_column('profiles', 'restored_at')
    op.drop_column('profiles', 'deleted_at')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
